site_name: Kickstarter
site_url: https://codestrange.github.io/kickstarter
repo_url: https://github.com/codestrange/kickstarter
edit_uri: ""

theme:
  name: material
  language: es
  features:
    - navigation.instant
  palette:
    primary: black
    accent: light blue

nav:
  - Kickstarter y el Misterio de los Juegos de Mesa: index.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs
