[tool.poetry]
name = "kickstarter"
version = "1.1.0"
description = ""
authors = ["leynier <leynier41@gmail.com>"]
homepage = "https://github.com/codestrange/kickstarter"
repository = "https://github.com/codestrange/kickstarter"
documentation = "https://github.com/codestrange/kickstarter"
readme = "README.md"
license = "MIT"

[tool.poetry.scripts]
kickstarter = "kickstarter.main:app"

[tool.poetry.dependencies]
python = "^3.8"
typer = "^0.3.2"
streamlit = "^0.77.0"
pydantic = "^1.7.3"
plotly = "^4.14.1"
scipy = "^1.5.4"
tabulate = "^0.8.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
flake8 = "^3.8.4"
black = "^20.8b1"
isort = "^5.6.4"
pytest-cov = "^2.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
